### ISSUE TITLE
web3wallet

### ISSUE THREAD

**Issue by jakobuid** [WalletConnect/WalletConnectKotlinV2#519]
- [x] Create a wallet sdk module dependent on Sign and Auth SDK
- [x] Extract WalletClient along with WalletInterface
- [x] Refactor SignInterface to split into SignWalletInterface and SignDappInterface
- [x] Refactor AuthInterface to split into AuthWalletInterface and AuthDappInterface
- [ ] Prepare MavenCentral publishing
- [x] Integrate WalletSDK into sample apps (Wallet and Responder)

Interface: https://gist.github.com/pedrouid/4067a262550ffb80ea93ab21cedba2fb
