### ISSUE TITLE
Verify API

### ISSUE THREAD

**Issue by jakubuid** [WalletConnect/WalletConnectKotlinV2#739]
Specs: https://github.com/WalletConnect/walletconnect-docs/pull/436/files

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/740
- [x] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/844
- [ ] Native Dapp attestation
```
