### ISSUE TITLE
Push Epic #2 Sync Integration/SDK Hardening

### ISSUE THREAD

**Issue by TalhaAli00** [WalletConnect/WalletConnectKotlinV2#809]
```[tasklist]
### Tasks
- [ ] #527
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/950
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/952
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1015
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1009
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1043
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1041
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1024
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/988
- [ ] IT for W3I SDK - Push/Notify part
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1042
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1065
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1066
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1067
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1074
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1075
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1100
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/1101
- [ ] Implement Jwt validation of issuer and expiry
```
