### ISSUE TITLE
Web3Modal Milestone #2

### ISSUE THREAD

**Issue by kacperoak** [WalletConnect/WalletConnectKotlinV2#887]
List of task for milestone #2

- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/917
- [x] #894
- [x] #895
- [x] #890
- [x] #891
- [x] #892
- [x] #893
- [x] #896
- [x] Adapt views to Light/Dark theme according to OS setup
- [x] Add "What is a wallet" screen
- [x] #897
