### ISSUE TITLE
Walletconnect

### ISSUE THREAD

**Issue by Chineduolu** [WalletConnect/WalletConnectKotlinV2#989]
**Describe the bug**

**SDK Version**
 - Client: [e.g.  Kotlin]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. Pixel]
 - OS: [e.g. Android 12]
 - Browser [e.g. stock browser, chrome]

**Additional context**

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/988
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/917
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/pull/986
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/977
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/pull/983
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/984
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/pull/985
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/pull/982
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/pull/987
- [ ] https://github.com/WalletConnect/WalletConnectKotlinV2/issues/809
```
